// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-mMctf34sXPNm1WHkm6qAGge28x7vuuM',
    appId: '1:711127594512:web:f8ba329d2508afd51cbc95',
    messagingSenderId: '711127594512',
    projectId: 'examen2-8a53e',
    authDomain: 'examen2-8a53e.firebaseapp.com',
    storageBucket: 'examen2-8a53e.appspot.com',
    measurementId: 'G-XSPBN68PXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0tqPH9ReQ-EOQWHZWW8uMB9DO-86LEWQ',
    appId: '1:711127594512:android:99482c7ce5bc6a691cbc95',
    messagingSenderId: '711127594512',
    projectId: 'examen2-8a53e',
    storageBucket: 'examen2-8a53e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU-vzamqPPgpnzbMi8xN_AlnZQK3L7yko',
    appId: '1:711127594512:ios:55318e6c4c9ef44d1cbc95',
    messagingSenderId: '711127594512',
    projectId: 'examen2-8a53e',
    storageBucket: 'examen2-8a53e.appspot.com',
    iosBundleId: 'com.example.examen2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU-vzamqPPgpnzbMi8xN_AlnZQK3L7yko',
    appId: '1:711127594512:ios:55318e6c4c9ef44d1cbc95',
    messagingSenderId: '711127594512',
    projectId: 'examen2-8a53e',
    storageBucket: 'examen2-8a53e.appspot.com',
    iosBundleId: 'com.example.examen2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-mMctf34sXPNm1WHkm6qAGge28x7vuuM',
    appId: '1:711127594512:web:e3b5f5b26eeae1131cbc95',
    messagingSenderId: '711127594512',
    projectId: 'examen2-8a53e',
    authDomain: 'examen2-8a53e.firebaseapp.com',
    storageBucket: 'examen2-8a53e.appspot.com',
    measurementId: 'G-2JS1N5S29V',
  );
}
